// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dtvdKAevEVhEvaIeNMcNNNq30HykN10',
    appId: '1:185767570250:web:237cfa061edc9867712fb3',
    messagingSenderId: '185767570250',
    projectId: 'kalmado-appdev',
    authDomain: 'kalmado-appdev.firebaseapp.com',
    databaseURL: 'https://kalmado-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalmado-appdev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNuQiQC_F1_LLOnxugupSrX234CKhSl4',
    appId: '1:185767570250:android:219611f772b8de2b712fb3',
    messagingSenderId: '185767570250',
    projectId: 'kalmado-appdev',
    databaseURL: 'https://kalmado-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalmado-appdev.firebasestorage.app',
  );
}
